export const skillset = [
  "Semantic & accessible HTML",
  "React Router",
  "Promises, Async/Await",
  "Responsive Web Design",
  "Redux-Saga",
  "GitHub Pull Requests & Review",
  "Teamwork",
  "Redux (Toolkit)",
  "Trello",
  "Markdown",
  "React Hooks",
  "Immutability",
  "Error handling",
  "NPM",
  "CSS BEM convention",
  "Working with API (fetch, axios)",
  "React",
  "SCSS",
  "CSS Grid",
  "JavaScript: ES6+",
  "Git",
  "CSS Flexbox",
  "CMS Wordpress",
  "MySQL",
  "TypeScript"
];